# create a service account and use it in your pod spec
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::492811607193:role/test-oidc
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default # kube-system # 
spec:
  serviceAccountName: aws-test # aws-load-balancer-controller  # 
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  tolerations:
  - operator: Exists
    effect: NoSchedule

# this works with kube-system name space